private
textFeatures
^ '"New features of the PNtalk System.
========================

- A new graphic user interface (GUI) allowing to edit nets. 
-- The editor can be open by menu command <open editor>.
-- Each change in the editor is carried across the source code. 
-- If the net''s source code is changed, it is necessary to regenerate graphic view of the net (menu command <clear and open editor>).

- Fixed problems with deallocation of simulation objects.

- A possibility to use breakpoints during simulation and inspect current states.

- Simulation server for remote working with models and simulations. It is experimental implementation which can be tested, e.g., by a telnet tool. The server will be part of a complex solution of the PNtalk system.

"'.